USE sales_data_sample;   -- USE TABLE

-- VIEW ENTIRE TABLE
SELECT * FROM dataanalytics;

-- GET TOTALS
SELECT COUNT(*) AS Total_records,
		COUNT(DISTINCT ï»¿OrderID) AS Total_Order, COUNT(DISTINCT CUSTOMERID) AS Total_Customer, COUNT(DISTINCT PRODUCT) AS Total_Product,
        COUNT(DISTINCT PAYMENTMETHOD) AS Payment_Methods, COUNT(DISTINCT REFERRALSOURCE) AS Referrer_Source,
        FORMAT((SUM(TOTALPRICE)),'N2') AS Total_Revenue, FORMAT(MAX(TOTALPRICE),'N2') AS Highest_Price, FORMAT((SUM(TOTALPRICE))/COUNT(DISTINCT ï»¿OrderID),'N2') AS AOV,
        MIN(TOTALPRICE) AS Lowest_Price, FORMAT((COUNT(DISTINCT ï»¿OrderID)/COUNT(DISTINCT CUSTOMERID)),'N2') as Purchase_Frequency, 
        FORMAT(SUM(QUANTITY),'N2') AS Qantity, FORMAT(AVG(QUANTITY),'N2') AS Avg_Qantity
	FROM dataanalytics;

    
 -- FIND DUPLICATE IDS
SELECT ï»¿OrderID,
       COUNT(*) AS Duplicate_Count
FROM dataanalytics
GROUP BY ï»¿OrderID
HAVING COUNT(*) > 1;   

 -- REPEATING CUSTOMERS IDS
SELECT CUSTOMERID,
       COUNT(*) AS Duplicate_Count
FROM dataanalytics
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;   

-- GET REVENUE BY PRODUCTS
SELECT PRODUCT,
	COUNT(*) AS order_count,
    FORMAT(SUM(TOTALPRICE),'N2') AS Revenue
FROM dataanalytics
GROUP BY PRODUCT
ORDER BY Revenue DESC;


-- GET ORDER BY PRODUCTS
SELECT PRODUCT,
    FORMAT(SUM(QUANTITY),'N2') AS Total_Quantity
FROM dataanalytics
GROUP BY PRODUCT
ORDER BY Total_Quantity DESC;


-- GET TOTAL ORDER BY STATUS
SELECT ORDERSTATUS,
       COUNT(*) AS Total
FROM dataanalytics
GROUP BY ORDERSTATUS;
 
 
 -- GET CANCELLED ORDERS
SELECT *
FROM dataanalytics
WHERE ORDERSTATUS = 'Cancelled';

 -- GET PENDING ORDERS
SELECT *
FROM dataanalytics
WHERE ORDERSTATUS = 'Pending'; 


-- GET SHIPPED ORDERS
SELECT *
FROM dataanalytics
WHERE ORDERSTATUS = 'Shipped'; 

-- GET DELIVERED ORDERS
SELECT *
FROM dataanalytics
WHERE ORDERSTATUS = 'Delivered';


-- TOTAL ORDER BY PAYMENT METHOD
SELECT PAYMENTMETHOD,
       COUNT(*) AS Orders
FROM dataanalytics
GROUP BY PAYMENTMETHOD
ORDER BY Orders DESC;

-- TOTAL REVENUE BY PAYMENT METHOD
SELECT PAYMENTMETHOD,
       FORMAT(SUM(TOTALPRICE),'N2') AS Total_Revenue
FROM dataanalytics
GROUP BY PAYMENTMETHOD
ORDER BY Total_Revenue DESC;


-- ORDERS WITH COUPON CODE
SELECT COUNT(*) AS Coupon_Orders
FROM dataanalytics
WHERE COUPONCODE IS NOT NULL;

-- ORDERS WITHOUT COUPON CODE
SELECT COUNT(*) AS No_Coupon_Orders
FROM dataanalytics
WHERE COUPONCODE IS NULL;


-- ORDERS WITH REDERRAL CODE
SELECT COUNT(*) AS Rederral_Order
FROM dataanalytics
WHERE REFERRALSOURCE IS NOT NULL;


-- ORDERS WITHOUT REDERRAL CODE
SELECT COUNT(*) AS Rederral_Order
FROM dataanalytics
WHERE REFERRALSOURCE IS NULL OR REFERRALSOURCE ='';


-- TOP 10 SPENDING CUSTOMER
SELECT CUSTOMERID,
       FORMAT(SUM(TOTALPRICE),'N2') AS Total_Spent
FROM dataanalytics
GROUP BY CustomerID
ORDER BY CUSTOMERID ASC
LIMIT 10;

-- TOP 10 HIGHEST ORDER
SELECT ï»¿OrderID AS OrderID,
       FORMAT(SUM(TOTALPRICE),'N2') AS Revenue
FROM dataanalytics
GROUP BY OrderID
ORDER BY Revenue ASC
LIMIT 10;


-- YEARLY SALES
SELECT YEAR(Date) AS Year,
       FORMAT(SUM(TotalPrice),'N2') AS Revenue
FROM dataanalytics
GROUP BY YEAR(Date);

-- MONTHLY ORDER
SELECT MONTH(Date) AS Month,
       COUNT(*) AS Orders
FROM dataanalytics
GROUP BY MONTH(Date)
ORDER BY Month ASC;


-- MONTHLY SALES
SELECT MONTH(Date) AS Month,
       FORMAT(SUM(TOTALPRICE),'N2') AS Total_Sales
FROM dataanalytics
GROUP BY MONTH(Date)
ORDER BY Month ASC;


-- MOST POPULAR PRODUCT 
SELECT PRODUCT,
       COUNT(*) AS Frequency
FROM dataanalytics
GROUP BY PRODUCT
ORDER BY Frequency DESC
LIMIT 1;


-- 13. Revenue by referral source
SELECT ReferralSource,
       SUM(TotalPrice) AS Revenue
FROM Cleaned_Dataset
GROUP BY ReferralSource
ORDER BY Revenue DESC;

-- NUMBER OF CUSTOMER PER REFERRAL SOURCE
SELECT REFERRALSOURCE,
       COUNT(DISTINCT CUSTOMERID) AS Customers
FROM dataanalytics
GROUP BY REFERRALSOURCE;